name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: './.github/actions/nix'
      with:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
        CACHIX_CACHE: nmattia-com
    - name: "Run tests"
      run: nix-build -o build --max-jobs 4
    - name: "Deploy to Netlify"
      if: github.ref == 'refs/heads/master'
      uses: netlify/actions/cli@feeabbe5daa2a48493ce68cbac6ead466e917f7b
      with:
        args: deploy --dir=$(readlink ./build) --message="$GITHUB_SHA" --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

